type Well {
    id: ID!,
    name: String,
    number: Int,
    type: String,
    api: Int,
    operator: String,
    lease: String,
    leaseNum: Int,
    fieldList: String,
    latitude: Float,
    longitude: Float,
    completionDepth: Int,
    trueVerticalDepth: Int,
    wellBoreProfile: String,
    isOn: Boolean,
    date: String,
    # production: [Production],
    # report: [Report],
    # recompletion: [Recompletion]
}

type Production {
    id: ID!
    oil: Int,
    gas: Int,
    water: Int,
    casingPSI: Int,
    tubingPSI: Int,
    choke: Int,
    # date: Date!
}

type Report {
    id: ID!,
    title: String,
    type: String,
    summary: String,
    supervisor: String,
    cost: Float,
    # date: Date!
}

type Query {
    getWells: Well,
    production: Production
}
